### ISSUE TITLE
Sending Messages along with value.

### ISSUE THREAD

**Issue by KhushalPShah** [JakeSCahill/iota-samples#10]
Is there a way to send a message while making a payment to CDA, along with the value?
I see that a CDA only sends the value. What necessary changes must be made to send a message along with the value in the transaction?

**Comment by JakeSCahill** [comment]
Hey @KhushalPShah , it's not possible at the moment, but the client library devs are working on it.

You can keep up to date by watching the [client library repositories](https://github.com/iotaledger), or you can go to the clients-discussion channel on [Discord](https://discord.iota.org/).

**Comment by KhushalPShah** [comment]
Alright.
Thanks.
Should I open up an issue on the client repository?

**Comment by JakeSCahill** [comment]
Yes, please do 😄 

[Go](https://github.com/iotaledger/iota.go/issues/new)
[Java](https://github.com/iotaledger/iota-java/issues/new)
[JavaScript](https://github.com/iotaledger/iota.js/issues/new)
